#!/bin/bash
#Bucle for utilizado para comprobar si existen los diferentes archivos necesarios,
#si no existen la ejecucion se detiene
for i in entrada.txt emisor.c clasifica.c imprimir.c leer.c estadistica.c datos.h makefile
do
    if [ -e $i ]
    then
      echo Existe $i
    else
      echo No existe el archivo $i
      exit
    fi
    done

make
./emisor < entrada.txt | ./clasifica | (./estadistica 2> minmax.txt |sort -n) > mediacat.txt
